language: java
jdk: openjdk12

services:
  - docker

script:
  - ./gradlew build
  - ./gradlew buildProdDocker
  - docker run -d -p8082:8080 polygloat/polygloat
  - cd clientapp
  - npm install
  - npx cypress run --spec cypress/integration/login.spec.js