version: '3'
services:
  postgres:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
#  app:
#    image: polygloat
#    ports:
#      - "8090:8080"
volumes:
  db-data:
