version: '3'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    image: polygloat/polygloat
    ports:
      - "8090:8080"
      - "8091:8091"
    env_file:
      - .env
    depends_on:
      - "db"
