version: '3'

services:
  db:
    image: postgres:11
    #volumes:
    #  - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
  #    ports:
  #      - "5432:5432"
  app:
    image: polygloat/polygloat
    ports:
      - "8090:8080"
      - "8091:8091"
    env_file:
      - .env
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8091,server=y,suspend=n
    depends_on:
      - "db"
#volumes:
#  db-data:
