package com.polygloat.constants;

import lombok.Getter;

public enum Message {
    THIRD_PARTY_AUTH_NO_EMAIL(),
    THIRD_PARTY_UNAUTHORIZED(),
    THIRD_PARTY_UNKNOWN_ERROR("third_party_auth_unknown_error"),
    THIRD_PARTY_AUTH_ERROR_MESSAGE(),
    USERNAME_OR_PASSWORD_INVALID(),
    BAD_CREDENTIALS(),
    USERNAME_ALREADY_EXISTS(), REGISTRATIONS_NOT_ALLOWED(), OPERATION_NOT_PERMITTED(),
    INVITATION_CODE_DOES_NOT_EXIST_OR_EXPIRED(),
    USER_ALREADY_HAS_PERMISSIONS(), CAN_NOT_REVOKE_OWN_PERMISSIONS(), LANGUAGE_NAME_EXISTS(), RESOURCE_NOT_FOUND(), LANGUAGE_ABBREVIATION_EXISTS(),
    VALIDATION_ERROR,
    SOURCE_EXISTS(), DATA_CORRUPTED(), LANGGUAGE_NOT_FOUND(), TRANSLATION_TEXT_IS_REQUIRED(), USER_NOT_FOUND(), REPOSITORY_NOT_FOUND(), SCOPE_NOT_FOUND(),
    API_KEY_NOT_FOUND();

    @Getter
    String code;

    Message(String code) {
        this.code = code;
    }

    Message() {
        this.code = this.name().toLowerCase();
    }
}
