name: Base workflow

on:
  push:
    barnches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build docker image
        run: ./gradlew buildProdDocker
      - name: Run the image
        run: docker run -d -p8082:8080 --name app polygloat/polygloat
      - name: Wait for running container
        run: 'until docker logs --since 5m app | grep -m 1 "started on port(s): 8080"; do : ;done'
      - name: Cypress tests
        run: ./gradlew cypress
      - name: Upload test report artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: build/reports
      - name: Upload cypress videos
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: build/clientapp/cypress/videos
